version: '3.5'
services:
  # app:
  #   container_name: flask_app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   ports:
  #     - "5000:5000"
  #   command: [ "flask", "run", "--host", "0.0.0.0" ]
  #   depends_on:
  #     - db

  db:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql
    
  redis:
    image: redis:6-alpine
    ports:
        - "6379:6379"
    tty: true
    stdin_open: true

volumes:
  db_volume: