site_name: demo-flask-sql-redis-celery
repo_url: https://github.com/Nguyen2442/demo-flask-sql-redis-celery
site_url: https://Nguyen2442.github.io/demo-flask-sql-redis-celery
site_description: This is a template repository for Python projects that use Poetry for their dependency management.
site_author: NguyenNT65
edit_uri: edit/main/docs/
repo_name: Nguyen2442/demo-flask-sql-redis-celery
copyright: Maintained by <a href="https://Nguyen2442.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Nguyen2442/demo-flask-sql-redis-celery
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/demo-flask-sql-redis-celery

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true